INSERT INTO owners (name, job, age) VALUES ('Cicely','Assistant Professor',55);
INSERT INTO owners (name, job, age) VALUES ('Filbert','Director of Sales',91);
INSERT INTO owners (name, job, age) VALUES  ('Maggie','Director of Sales',84);
INSERT INTO owners (name, job, age) VALUES ('Robinet','Health Coach III',58);
INSERT INTO owners (name, job, age) VALUES ('Norbie','Analyst Programmer',3);
INSERT INTO owners (name, job, age) VALUES ('Fran','VP Quality Control',20);
INSERT INTO owners (name, job, age) VALUES ('Roddie','Software Test Engineer III',98);
INSERT INTO owners (name, job, age) VALUES ('Lucretia','Environmental Tech',26);
INSERT INTO owners (name, job, age) VALUES ('Jarred','Software Engineer IV',60);
INSERT INTO owners (name, job, age) VALUES ('August','Assistant Media Planner',29);
INSERT INTO owners (name, job, age) VALUES ('Jae','Nurse Practicioner',50);
INSERT INTO owners (name, job, age) VALUES ('Hadleigh','VP Product Management',57);

INSERT INTO cars (make, model, year, owners_id) VALUES ('Suzuki','Kizashi',2012, 3);
INSERT INTO cars (make, model, year, owners_id) VALUES ('Mazda','626',1992, 12);
INSERT INTO cars (make, model, year, owners_id) VALUES ('Suzuki','Swift',1987, 6);
INSERT INTO cars (make, model, year, owners_id) VALUES ('Subaru','Forester',2001, 9);
INSERT INTO cars (make, model, year, owners_id) VALUES ('Mitsubishi','Montero',1998, 4);
INSERT INTO cars (make, model, year, owners_id) VALUES ('Honda','Accord',1989, 9);
INSERT INTO cars (make, model, year, owners_id) VALUES ('Chevrolet','Lumina APV',1992, 10);
INSERT INTO cars (make, model, year, owners_id) VALUES ('Ford','F150',2007, 7);
INSERT INTO cars (make, model, year, owners_id) VALUES ('GMC','Sierra 2500',2008, 8);
INSERT INTO cars (make, model, year, owners_id) VALUES ('Chevrolet','Cavalier',2000, 8);
INSERT INTO cars (make, model, year, owners_id) VALUES ('Toyota','Land Cruiser',2002, 3);
INSERT INTO cars (make, model, year, owners_id) VALUES ('Chevrolet','S10',2003, 4);
INSERT INTO cars (make, model, year, owners_id) VALUES ('Mazda','Mazdaspeed 3', 2012, 3);
INSERT INTO cars (make, model, year, owners_id) VALUES ('Ford','Ranger', 1988, 8);
INSERT INTO cars (make, model, year, owners_id) VALUES ('Pontiac','Bonneville',2002, 1);
INSERT INTO cars (make, model, year, owners_id) VALUES ('Buick','Regal', 2012, 2);
INSERT INTO cars (make, model, year, owners_id) VALUES ('Ford','E350', 2005, 2);
INSERT INTO cars (make, model, year, owners_id) VALUES ('Hyundai','XG350', 2004, 8);
INSERT INTO cars (make, model, year, owners_id) VALUES ('Mercury','Grand Marquis', 1987, 1);
INSERT INTO cars (make, model, year, owners_id) VALUES ('Pontiac','Bonneville', 1997, 3);